### PR TITLE
Get it to build with clang on Ubuntu 14.04.

### PR DESCRIPTION
**Pull request by schneith**

### CODE REVIEW

**Comment by simonlynen** [comment]
lgtm

**Comment by schneith** [comment]
test this please

**Comment by PascalGohl** [comment]
Is there any reason to keep the Qt support for gcc? 
It started to make problems with ros image_view and disparity_view. I would like to turn it off in general.

**Comment by schneith** [comment]
Do the image windows work for you without it? If so, then there is no need for qt I think.

**Pull request merged**
